Add Construct query case to current ADT model
gsk-aiops/bellman-algebra-parser pull request #14
Opened 2021-01-21 19:44 UTC by shihch

2021-01-21 23:45 UTC, puremachinery requested changes
Remove commented line of code, otherwise seems good.

Other note: John recently checked in scalastyle - might be good to run that over this, but not required for approval.

2021-01-21 23:45 UTC, puremachinery commented on src/main/scala/QueryConstruct.scala
> +//    val q = Source.fromFile("src/test/resources/queries/q3-union.sparql").mkString
Any reason not to remove commented code?

2021-01-22 12:31 UTC, JNKHunter commented on src/main/scala/StringLike.scala
> +  final case class BLANK(ref:String) extends StringVal
Sweet! Was going to add Blank node support :)

2021-01-22 12:33 UTC, JNKHunter requested changes
Looks good Clark. There were some Scalastyle warnings (You can look at the 'checks' tab). If we could clear those out, I'm good to merge. We'll need to figure out how to have checks fail when scalastyle has warnings.

2021-01-22 19:09 UTC, shihch commented on src/main/scala/QueryConstruct.scala
> +//    val q = Source.fromFile("src/test/resources/queries/q3-union.sparql").mkString
The main method is removed, which is no need for now.

2021-01-22 19:15 UTC, shihch commented
scala style check is now passed.

2021-01-22 19:15 UTC, puremachinery approved these changes
Looks like this covers the comment and the scalastyle changes. Great.

2021-01-22 19:45 UTC, JNKHunter approved these changes

2021-01-22 19:47 UTC, merged